### ISSUE TITLE
Lag when breaking block

### ISSUE THREAD

**Issue by maicol07** [hugoalh/Minecraft.Java.DataPack.RecipePlus#1]
## Minecraft Version

```
20w09a (issue appeared also on 1.14.4)
```

## Version

```
3.0.0-I1
```

## Describe Issue

```
Datapack generates lag when breaking blocks (blocks do not break for a second or two)
```

**Comment by maicol07** [comment]
Any news? I've seen there is a 4.0 version in development...

**Comment by hugoalh** [comment]
> Any news? I've seen there is a 4.0 version in development...

Yes, 4.0 is in developing (but due to some issue on Minecraft Java, 4.0 only support 1.15+), and there has tons of things need to add (around 500+) and fix (not just this issue, about 15 issues which reported in other places).

For the lag issue, it looks like cause by the auto crafting and drop item crafting, still considering to remove those feature or not.

**Comment by hugoalh** [comment]
Seems fixed in 4.0.0-E1.

**Comment by maicol07** [comment]
When will 4.0.0-E1 be released?

**Comment by hugoalh** [comment]
I cannot confirm the release date since there still have other issues must
resolve firstly.

If all things go well, the earliest release date of 4.0.0 (for 1.15) will
be at the middle of June, and 5.0.0 (for 1.16) will be at the end of June.

**Comment by maicol07** [comment]
👍 , I was using the 3.0.0 with 1.16 and the only bug was this one. Will try at June!
Thank you for your work
